---
variables:
  GITLAB_CI_IMAGE_ANSIBLE: 'librespace/ansible:2.9.4'
  GITLAB_CI_IMAGE_PYTHON: 'python:3.8.6'
  GITLAB_CI_PYPI_YAMLLINT: 'yamllint~=1.20.0'
stages:
  - static
  - build
static:
  stage: static
  image: ${GITLAB_CI_IMAGE_PYTHON}
  before_script:
    - pip install "$GITLAB_CI_PYPI_YAMLLINT"
  script:
    - cd ansible
    - 'yamllint -s *inventory'
docs:
  image: fedora
  stage: build
  script:
    - dnf -y update
    - dnf -y install texlive-collection-latex texlive-collection-latexrecommended texlive-lipsum texlive-glossaries texlive-circuitikz
    - dnf -y install make cmake
    - cd doc
    - mkdir build
    - cd build
    - cmake ..
    - make pdf
  artifacts:
    paths:
      - doc/build/*.pdf
