---
- name: Set attributes of files
  file:
    access_time: '{{ item.access_time | default(omit) }}'
    access_time_format: '{{ item.access_time_format | default(omit) }}'
    attributes: '{{ item.attirbutes | default(omit) }}'
    follow: '{{ item.follow | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
    modification_time: '{{ item.modification_time | default(omit) }}'
    modification_time_format: '{{ item.modification_time_format | default(omit) }}'
    owner: '{{ item.owner | default(omit) }}'
    path: '{{ item.path | default(omit) }}'
    recurse: '{{ item.recurse | default(omit) }}'
    selevel: '{{ item.selevel | default(omit) }}'
    serole: '{{ item.serole | default(omit) }}'
    setype: '{{ item.setype | default(omit) }}'
    seuser: '{{ item.seuser | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'
  with_items: '{{ files | default([]) }}'
  when: files is not none
  become: true
  tags:
    - files
- name: Copy files
  copy:
    attributes: '{{ item.attributes | default(omit) }}'
    backup: '{{ item.backup | default(omit) }}'
    checksum: '{{ item.checksum | default(omit) }}'
    content: '{{ item.content | default(omit) }}'
    decrypt: '{{ item.decrypt | default(omit) }}'
    dest: '{{ item.dest | default(omit) }}'
    directory_mode: '{{ item.directory_mode | default(omit) }}'
    follow: '{{ item.follow | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    local_follow: '{{ item.local_follow | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
    owner: '{{ item.owner | default(omit) }}'
    remote_src: '{{ item.remote_src | default(omit) }}'
    selevel: '{{ item.selevel | default(omit) }}'
    serole: '{{ item.serole | default(omit) }}'
    setype: '{{ item.setype | default(omit) }}'
    seuser: '{{ item.seuser | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'
    validate: '{{ item.validate | default(omit) }}'
  with_items: '{{ copies | default([]) }}'
  when: copies is not none
  become: true
  tags:
    - files
- name: Template files out
  template:
    attributes: '{{ item.attributes | default(omit) }}'
    backup: '{{ item.backup | default(omit) }}'
    block_end_string: '{{ item.block_end_string | default(omit) }}'
    block_start_string: '{{ item.block_start_string | default(omit) }}'
    dest: '{{ item.dest | default(omit) }}'
    follow: '{{ item.follow | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    lstrip_blocks: '{{ item.lstrip_blocks | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
    newline_sequence: '{{ item.newline_sequence | default(omit) }}'
    output_encoding: '{{ item.output_encoding | default(omit) }}'
    owner: '{{ item.owner | default(omit) }}'
    selevel: '{{ item.selevel | default(omit) }}'
    serole: '{{ item.serole | default(omit) }}'
    setype: '{{ item.setype | default(omit) }}'
    seuser: '{{ item.seuser | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    trim_blocks: '{{ item.trim_blocks | default(omit) }}'
    unsafe_writes: '{{ item.unsafe_writes | default(omit) }}'
    validate: '{{ item.validate | default(omit) }}'
    variable_end_string: '{{ item.variable_end_string | default(omit) }}'
    variable_start_string: '{{ item.variable_start_string | default(omit) }}'
  with_items: '{{ templates | default([]) }}'
  when: templates is not none
  become: true
  tags:
    - files
- name: Synchronize files
  synchronize:
    archive: '{{ item.archive | default(omit) }}'
    checksum: '{{ item.checksum | default(omit) }}'
    compress: '{{ item.compress | default(omit) }}'
    copy_links: '{{ item.copy_links | default(omit) }}'
    delete: '{{ item.delete | default(omit) }}'
    dest: '{{ item.dest | default(omit) }}'
    dest_port: '{{ item.dest_port | default(omit) }}'
    dirs: '{{ item.dirs | default(omit) }}'
    existing_only: '{{ item.existing_only | default(omit) }}'
    group: '{{ item.group | default(omit) }}'
    link_dest: '{{ item.link_dest | default(omit) }}'
    links: '{{ item.links | default(omit) }}'
    mode: '{{ item.mode | default(omit) }}'
    owner: '{{ item.owner | default(omit) }}'
    partial: '{{ item.partial | default(omit) }}'
    perms: '{{ item.perms | default(omit) }}'
    private_key: '{{ item.private_key | default(omit) }}'
    recursive: '{{ item.recursive | default(omit) }}'
    rsync_opts: '{{ item.rsync_opts | default(omit) }}'
    rsync_path: '{{ item.rsync_path | default(omit) }}'
    rsync_timeout: '{{ item.rsync_timeout | default(omit) }}'
    set_remote_user: '{{ item.set_remote_user | default(omit) }}'
    src: '{{ item.src | default(omit) }}'
    times: '{{ item.times | default(omit) }}'
    use_ssh_args: '{{ item.use_ssh_args | default(omit) }}'
    verify_host: '{{ item.verify_host | default(omit) }}'
  with_items: '{{ synchronizes | default([]) }}'
  when: synchronizes is not none
  become: true
  tags:
    - files
