---
- name: Install filesystem managing utilities
  package:
    name: 'util-linux'
    state: 'present'
  when: ansible_distribution in ('CentOS')
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  become: true
  tags:
    - filesystem
- name: Create filesystems
  filesystem:
    dev: '{{ item.dev | default(omit) }}'
    force: '{{ item.force | default(omit) }}'
    fstype: '{{ item.fstype | default(omit) }}'
    opts: '{{ item.opts | default(omit) }}'
    resizefs: '{{ item.resizefs | default(omit) }}'
  with_items: '{{ filesystems | default([]) }}'
  when: filesystems is not none
  become: true
  tags:
    - filesystem
