---
- name: Enable firewalld
  service:
    name: 'firewalld'
    enabled: true
    state: 'started'
  become: true
  when: ansible_distribution in ('CentOS')
  tags:
    - firewall
- name: Add firewall rules
  firewalld:
    immediate: '{{ item.immediate | default(omit) }}'
    interface: '{{ item.interface | default(omit) }}'
    masquerade: '{{ item.masquerade | default(omit) }}'
    permanent: '{{ item.permanent | default(omit) }}'
    port: '{{ item.port | default(omit) }}'
    rich_rule: '{{ item.rich_rule | default(omit) }}'
    service: '{{ item.service | default(omit) }}'
    source: '{{ item.source | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    timeout: '{{ item.timeout | default(omit) }}'
    zone: '{{ item.zone | default(omit) }}'
  become: true
  with_items: '{{ firewall | default([]) }}'
  when: >-
    ansible_distribution in ('CentOS')
    and firewall is not none
  tags:
    - firewall
