---
- name: Install EPEL release
  package:
    name: 'epel-release'
    state: 'present'
  when: ansible_distribution in ('CentOS')
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  become: true
  tags:
    - packages
- name: Install packages
  package:
    name: '{{ item.name }}'
    state: '{{ item.state | default(omit) }}'
    use: '{{ item.use | default(omit) }}'
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  become: true
  with_items: '{{ packages | default([]) }}'
  when: packages is not none
  tags:
    - packages
