---
- name: Install parted
  package:
    name: 'parted'
    state: 'present'
  when: ansible_distribution in ('CentOS')
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  become: true
  tags:
    - parted
- name: Create partitions
  parted:
    align: '{{ item.align | default(omit) }}'
    device: '{{ item.device | default(omit) }}'
    flags: '{{ item.flags | default(omit) }}'
    label: '{{ item.label | default(omit) }}'
    name: '{{ item.name | default(omit) }}'
    number: '{{ item.number | default(omit) }}'
    part_end: '{{ item.part_end | default(omit) }}'
    part_start: '{{ item.part_start | default(omit) }}'
    state: '{{ item.state | default(omit) }}'
    unit: '{{ item.unit | default(omit) }}'
  become: true
  with_items: '{{ partitions | default([]) }}'
  when: partitions is not none
  tags:
    - parted
