---
- name: Install Git
  package:
    name: 'git'
    state: 'present'
  register: res
  until: res is success
  retries: '{{ package_retries }}'
  delay: '{{ package_delay }}'
  become: true
- name: Initialize Git repositories
  shell: 'git init --shared=0600 .'
  args:
    chdir: '{{ item.path }}'
    creates: '{{ item.path }}/.git'
  become: true
  when: git_track is not none
  with_items: '{{ git_track | default([]) }}'
  tags:
    - skip_ansible_lint
- name: Add exporting of Git environment variables to profile
  copy:
    dest: '/etc/profile.d/git-track.sh'
    content: |
      export GIT_COMMITTER_NAME="${GIT_COMMITTER_NAME:-$(git config --get user.name)}"
      export GIT_COMMITTER_EMAIL="${GIT_COMMITTER_EMAIL:-$(git config --get user.email)}"
      export GIT_AUTHOR_NAME="${GIT_AUTHOR_NAME:-$GIT_COMMITTER_NAME}"
      export GIT_AUTHOR_EMAIL="${GIT_AUTHOR_EMAIL:-$GIT_COMMITTER_EMAIL}"
  become: true
- name: Add Git variables to keep when using sudo
  copy:
    dest: '/etc/sudoers.d/git-track'
    mode: 'a-w,o-rw'
    content: |
      Defaults    env_keep += "GIT_COMMITTER_NAME GIT_COMMITTER_EMAIL GIT_AUTHOR_NAME GIT_AUTHOR_EMAIL"
      Defaults    env_keep += "EDITOR"
  become: true
- name: Update index with all changes to working dir
  shell: 'git add -A && git commit -m "{{ git_track_message | default("Ansible Git track changes") }}"'
  args:
    chdir: '{{ item.path }}'
  environment:
    GIT_COMMITTER_NAME: '{{ item.name }}'
    GIT_COMMITTER_EMAIL: '{{ item.email }}'
    GIT_AUTHOR_NAME: '{{ item.name }}'
    GIT_AUTHOR_EMAIL: '{{ item.email }}'
  with_items: '{{ git_track | default([]) }}'
  register: git_add_res
  failed_when: false
  changed_when: git_add_res.rc == 0
  become: true
  when: git_track is not none
  tags:
    - skip_ansible_lint
